- name: Instalar dependencias
      run: npm install
      working-directory: ./WEB  # Pon aquí el nombre de la carpeta

    - name: Compilar proyecto
      run: npm run build
      working-directory: ./WEB
